/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Table */

#ifndef _Included_application_Table
#define _Included_application_Table
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Table
 * Method:    infixToPostfix
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_Table_infixToPostfix
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
